Initial commit

diff --git a/.gitea/workflows/ci.yaml b/.gitea/workflows/ci.yaml
--- a/.gitea/workflows/ci.yaml
+++ b/.gitea/workflows/ci.yaml
@@ -28,6 +28,7 @@ jobs:
             docker_context: build
             ecr_repo: auth-service
             go_version: "1.23"
+            serv_port: 8001
 
           - service: flag
             language: python
@@ -36,6 +37,7 @@ jobs:
             docker_context: build
             ecr_repo: flag-service
             python_version: "3.12"
+            serv_port: 8002
 
           - service: targeting
             language: python
@@ -44,6 +46,7 @@ jobs:
             docker_context: build
             ecr_repo: targeting-service
             python_version: "3.12"
+            serv_port: 8003
 
           - service: evaluation
             language: go
@@ -52,6 +55,7 @@ jobs:
             docker_context: build
             ecr_repo: evaluation-service
             go_version: "1.23"
+            serv_port: 8004
 
           - service: analytics
             language: python
@@ -60,13 +64,14 @@ jobs:
             docker_context: build
             ecr_repo: analytics-service
             python_version: "3.12"
+            serv_port: 8005
 
     steps:
       # 1. Checkout
       - name: Checkout code
         uses: actions/checkout@v6
 
-      # Setup das linguagens
+      # Setup do Go e do Python
       - name: Setup Go
         if: matrix.language == 'go'
         uses: actions/setup-go@v6
@@ -83,15 +88,31 @@ jobs:
       - name: Build e Unit Test (Go)
         if: matrix.language == 'go'
         working-directory: ${{ matrix.code_dir }}
-        run: go test ./... -v
+        run: |
+          export PORT="${{ matrix.serv_port }}"
+          export MASTER_KEY="admin123"
+          export REDIS_URL="redis://localhost:6379"
+          export FLAG_SERVICE_URL="http://localhost:8002"
+          export TARGETING_SERVICE_URL="http://localhost:8003"
+          export AWS_SQS_URL="https://sqs.us-east-1.amazonaws.com/123456789012/sua-fila"
+          export AWS_REGION="${{ secrets.AWS_REGION }}"
+          go mod tidy
+          go run .
+          curl -fs "http://localhost:${{ matrix.serv_port }}/health" && echo "Health OK" || echo "Health FAIL"
 
       - name: Build e Unit Test (Python)
         if: matrix.language == 'python'
         working-directory: ${{ matrix.code_dir }}
         run: |
-          pip install -r requirements.txt pytest
-          # Se não houver testes, o pytest retorna código 5 > não falha o pipeline
-          pytest --tb=no || [ $? -eq 5 ] || exit 1
+          export PORT="${{ matrix.serv_port }}"
+          export DATABASE_URL="postgres://SEU_USUARIO:SUA_SENHA@localhost:5432/flags_db"
+          export AUTH_SERVICE_URL="http://localhost:${{ matrix.serv_port }}"
+          export AWS_SQS_URL="https://sqs.us-east-1.amazonaws.com/123456789012/sua-fila"
+          export AWS_DYNAMODB_TABLE="ToggleMasterAnalytics"
+          export AWS_REGION="${{ secrets.AWS_REGION }}"
+          pip install -r requirements.txt
+          gunicorn --bind 0.0.0.0:${{ matrix.code_dir }} app:app
+          curl -fs "http://localhost:${{ matrix.serv_port }}/health" && echo "Health OK" || echo "Health FAIL"
 
       # # 3. Linter / Static Analysis
       # - name: Linter (Go - golangci-lint)
